---
swagger: "2.0"
info:
  description: "STS - Sales Transaction Microservice"
  version: "1.0.0"
  title: "Sales Transaction APIs"
  contact:
    email: "priyadharshini.nehru@daimler.com"
host: "virtserver.swaggerhub.com"
basePath: "/S459/STS/1.0.0"
tags:
- name: "STS - customer"
  description: "Endpoints related to customer"
- name: "STS - sales transaction"
  description: "Endpoints related to sales transaction"
- name: "STS - quote"
  description: "Endpoints related to quotes"
- name: "STS - order"
  description: "Endpoints related to orders"
schemes:
- "https"
paths:
  /salestxn:
    get:
      tags:
      - "sales transaction - sales query"
      summary: "Retrieves sales transactions in STS for a particular customer"
      description: "By passing in the appropriate options, you can retreive the sales\
        \ transactions of a particular customer \n"
      operationId: "GetSalesTxnsForCustomer"
      produces:
      - "application/json"
      parameters:
      - name: "custId"
        in: "query"
        description: "pass the customerId to get the sales txns"
        required: true
        type: "string"
      - name: "skip"
        in: "query"
        description: "number of records to skip for pagination"
        required: false
        type: "integer"
        minimum: 0
        format: "int32"
      - name: "limit"
        in: "query"
        description: "maximum number of records to return"
        required: false
        type: "integer"
        maximum: 50
        minimum: 0
        format: "int32"
      responses:
        200:
          description: "search results matching customerId"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SalesTxnResponseDto"
        400:
          description: "bad input parameter"
    post:
      tags:
      - "sales transaction - sales query"
      summary: "Creates a new sales transaction/sales query in STS"
      description: "Creates a new sales txn in STS\n"
      operationId: "CreateSalesTransaction"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "getSimilarVehicle"
        in: "query"
        description: "pass an optional 'true/false' flag to retrieve the vehicle info\
          \ if the currently searched vehicle is unavailable"
        required: false
        type: "boolean"
        default: false
      - in: "body"
        name: "salesTxnReq"
        description: "sales transaction to be created in STS"
        required: true
        schema:
          $ref: "#/definitions/SalesTxnReqDto"
      responses:
        201:
          description: "item created"
          schema:
            $ref: "#/definitions/SalesTxnResponseDto"
        400:
          description: "bad input parameter"
  /salestxn/{stId}:
    get:
      tags:
      - "sales transaction - sales query"
      summary: "Retrieves sales transactions in STS for a sales transaction id"
      description: "By passing the stId, you can retreive a specific sales transaction\n"
      operationId: "GetSalesTxnById"
      produces:
      - "application/json"
      parameters:
      - name: "stId"
        in: "path"
        description: "pass the stId to get the sales txn"
        required: true
        type: "integer"
      responses:
        200:
          description: "sales transaction for the stId retreived"
          schema:
            $ref: "#/definitions/SalesTxnResponseDto"
        400:
          description: "bad input parameter"
    delete:
      tags:
      - "sales transaction - sales query"
      summary: "cancels a sales transactions in STS for a sales transaction id,by\
        \ updating the sales txn status"
      description: "By passing the stId, you can cancel a specific sales transaction\n"
      operationId: "CancelSalesTxnById"
      produces:
      - "application/json"
      parameters:
      - name: "stId"
        in: "path"
        description: "pass the stId to get the sales txn"
        required: true
        type: "integer"
      - name: "custId"
        in: "query"
        description: "CustomerId"
        required: true
        type: "integer"
      responses:
        200:
          description: "sales transaction for cancellation"
          schema:
            $ref: "#/definitions/SalesTxnSimpleResponseDto"
        400:
          description: "bad input parameter"
  /salestxn/query:
    post:
      tags:
      - "sales transaction - quote"
      summary: "Creates a new quote in STS for the sales transaction"
      description: "Creates a quote for a sales txn in STS\n"
      operationId: "CreateQuoteForSalesTransaction"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "quoteReq"
        description: "quote request to be passed from salestouch web to create a quote\
          \ for a sales txn in STS"
        required: true
        schema:
          $ref: "#/definitions/QuoteReqDto"
      responses:
        201:
          description: "item created"
          schema:
            $ref: "#/definitions/QuoteResponseDto"
        400:
          description: "bad input parameter"
definitions:
  SalesTxnReqDto:
    type: "object"
    required:
    - "commNo"
    - "custId"
    properties:
      commNo:
        type: "string"
        example: "7017480851"
      custId:
        type: "integer"
        format: "int32"
        example: 123
    description: "Dto Object that is passed to the API for CRUD operations on the\
      \ Sales Transaction related to Sales Query"
    example:
      commNo: "7017480851"
      custId: 123
  SalesTxnSimpleResponseDto:
    type: "object"
    properties:
      StId:
        type: "integer"
        format: "int32"
        example: 1
      CustId:
        type: "integer"
        format: "int32"
        example: 123
      CreatedDate:
        type: "string"
        format: "int32"
        example: "12/11/2018 00:12:45"
      ModifiedDate:
        type: "string"
        format: "int32"
        example: "13/11/2018 00:12:45"
      CurrentStage:
        type: "string"
        example: "Sales transaction cancelled"
      CurrentStatus:
        type: "string"
        example: "Cancelled by Customer before quote"
    description: "Simple sales transaction Dto"
    example:
      CustId: 123
      CurrentStatus: "Cancelled by Customer before quote"
      CreatedDate: "12/11/2018 00:12:45"
      CurrentStage: "Sales transaction cancelled"
      StId: 1
      ModifiedDate: "13/11/2018 00:12:45"
  SalesTxnResponseDto:
    type: "object"
    properties:
      StId:
        type: "integer"
        format: "int32"
        example: 1
      CustId:
        type: "integer"
        format: "int32"
        example: 123
      CreatedDate:
        type: "string"
        format: "int32"
        example: "12/11/2018 00:12:45"
      ModifiedDate:
        type: "string"
        format: "int32"
        example: "13/11/2018 00:12:45"
      CurrentStage:
        type: "string"
        example: "Sales transaction Initiated"
      CurrentStatus:
        type: "string"
        example: "Vehicle Data returned successfully"
      VehicleData:
        $ref: "#/definitions/VehicleDataDto"
    description: "Complete sales transaction Dto (should include Sales Transaction,\
      \ Fleet details, Vehicle Data, Quote, Order, DIP, Taxes, DFS, etc.)"
    example:
      CustId: 123
      CurrentStatus: "Vehicle Data returned successfully"
      CreatedDate: "12/11/2018 00:12:45"
      CurrentStage: "Sales transaction Initiated"
      StId: 1
      ModifiedDate: "13/11/2018 00:12:45"
      VehicleData:
        IsSimilarVehicle: false
        VinNo: "W273647619E248762"
        VmsNo: 3456386
        VehicleEquipmentDetail:
          EngNo: 38746297
          Steering: "Cruise Control, Multifunction steering wheel"
          Transmission: "7G-TRONIC"
          EngCap: "1.595 cm3"
          ImageUrl: "./A_180_d_Automatic_Img.jpg"
          Interior:
          - "Thermatic, Panaromic sliding sunroof"
          - "Thermatic, Panaromic sliding sunroof"
          BodyType: "Coupe"
          IntRegYear: 2018
          Colour: "cosmos black metallic"
          vId: 8443163
          Design: "AMG Bodystyling"
          TransmissionType: "Manual"
          Upholstery: "man-made leather black"
          Output: "115 KW"
          SafetyAndTech:
          - "Active Park Assist, ECO start/stop function"
          - "Active Park Assist, ECO start/stop function"
          Communication:
          - "CD Player, E-Call"
          - "CD Player, E-Call"
        VehicleCurr: "EUR"
        VehicleName: "A 180 d Automatic"
        VehicleInitialPrice: 32868.47
  BasicVehicleDataDto:
    type: "object"
    properties:
      VmsNo:
        type: "integer"
        example: 3456386
      VinNo:
        type: "string"
        example: "W273647619E248762"
      VehicleModel:
        type: "string"
        example: "A 180 d Automatic"
      EngNo:
        type: "integer"
        example: 38746297
    description: "Dto object that holds basic vehicle information"
    example:
      EngNo: 38746297
      VinNo: "W273647619E248762"
      VmsNo: 3456386
      VehicleModel: "A 180 d Automatic"
  VehicleDataDto:
    type: "object"
    properties:
      VmsNo:
        type: "integer"
        example: 3456386
      VinNo:
        type: "string"
        example: "W273647619E248762"
      VehicleName:
        type: "string"
        example: "A 180 d Automatic"
      VehicleInitialPrice:
        type: "number"
        example: 32868.47
      VehicleCurr:
        type: "string"
        example: "EUR"
      IsSimilarVehicle:
        type: "boolean"
        example: false
      VehicleEquipmentDetail:
        $ref: "#/definitions/VEquipmentDetailsDto"
    description: "Contains the Vehicle data that is to be returned after sales query\
      \ is created successfully in STS"
    example:
      IsSimilarVehicle: false
      VinNo: "W273647619E248762"
      VmsNo: 3456386
      VehicleEquipmentDetail:
        EngNo: 38746297
        Steering: "Cruise Control, Multifunction steering wheel"
        Transmission: "7G-TRONIC"
        EngCap: "1.595 cm3"
        ImageUrl: "./A_180_d_Automatic_Img.jpg"
        Interior:
        - "Thermatic, Panaromic sliding sunroof"
        - "Thermatic, Panaromic sliding sunroof"
        BodyType: "Coupe"
        IntRegYear: 2018
        Colour: "cosmos black metallic"
        vId: 8443163
        Design: "AMG Bodystyling"
        TransmissionType: "Manual"
        Upholstery: "man-made leather black"
        Output: "115 KW"
        SafetyAndTech:
        - "Active Park Assist, ECO start/stop function"
        - "Active Park Assist, ECO start/stop function"
        Communication:
        - "CD Player, E-Call"
        - "CD Player, E-Call"
      VehicleCurr: "EUR"
      VehicleName: "A 180 d Automatic"
      VehicleInitialPrice: 32868.47
  VEquipmentDetailsDto:
    type: "object"
    properties:
      vId:
        type: "integer"
        example: 8443163
      BodyType:
        type: "string"
        example: "Coupe"
      Output:
        type: "string"
        example: "115 KW"
      TransmissionType:
        type: "string"
        example: "Manual"
      ImageUrl:
        type: "string"
        example: "./A_180_d_Automatic_Img.jpg"
      EngNo:
        type: "integer"
        example: 38746297
      EngCap:
        type: "string"
        example: "1.595 cm3"
      Colour:
        type: "string"
        example: "cosmos black metallic"
      Upholstery:
        type: "string"
        example: "man-made leather black"
      IntRegYear:
        type: "integer"
        example: 2018
      Design:
        type: "string"
        example: "AMG Bodystyling"
      Transmission:
        type: "string"
        example: "7G-TRONIC"
      Steering:
        type: "array"
        example: "Cruise Control, Multifunction steering wheel"
        items:
          format: "string"
      SafetyAndTech:
        type: "array"
        items:
          format: "string"
          example: "Active Park Assist, ECO start/stop function"
      Interior:
        type: "array"
        items:
          format: "string"
          example: "Thermatic, Panaromic sliding sunroof"
      Communication:
        type: "array"
        items:
          format: "string"
          example: "CD Player, E-Call"
    description: "Dto object for the currently selected vehicle details"
    example:
      EngNo: 38746297
      Steering: "Cruise Control, Multifunction steering wheel"
      Transmission: "7G-TRONIC"
      EngCap: "1.595 cm3"
      ImageUrl: "./A_180_d_Automatic_Img.jpg"
      Interior:
      - "Thermatic, Panaromic sliding sunroof"
      - "Thermatic, Panaromic sliding sunroof"
      BodyType: "Coupe"
      IntRegYear: 2018
      Colour: "cosmos black metallic"
      vId: 8443163
      Design: "AMG Bodystyling"
      TransmissionType: "Manual"
      Upholstery: "man-made leather black"
      Output: "115 KW"
      SafetyAndTech:
      - "Active Park Assist, ECO start/stop function"
      - "Active Park Assist, ECO start/stop function"
      Communication:
      - "CD Player, E-Call"
      - "CD Player, E-Call"
  QuoteReqDto:
    type: "object"
    required:
    - "commNo"
    - "custId"
    - "stId"
    properties:
      commNo:
        type: "string"
        example: "7017480851"
      custId:
        type: "integer"
        format: "int32"
        example: 123
      stId:
        type: "integer"
        format: "int32"
        example: 48652
      FinancingInfo:
        $ref: "#/definitions/FinProdDetailsDto"
      FleetDetails:
        $ref: "#/definitions/FleetDetailsDto"
    description: "Dto Object that is passed to the API for CRUD operations on the\
      \ Sales Transaction related to quote"
    example:
      commNo: "7017480851"
      FinancingInfo:
        productId: 3454
        monthlyPayment: 1000
        productTerm: 12
      FleetDetails:
        fleetVolume: 2
        fleetChannelId: 1
      custId: 123
      stId: 48652
  QuoteResponseDto:
    type: "object"
    required:
    - "custId"
    - "custUniqueId"
    - "plannedRetailDate"
    - "pricingDetails"
    - "quoteApprovedDate"
    - "quoteExpiryDate"
    - "quoteId"
    - "quoteStatus"
    - "stId"
    - "vehicleInfo"
    properties:
      quoteId:
        type: "integer"
        format: "int32"
        example: 1000801
      custId:
        type: "integer"
        format: "int32"
        example: 123
      stId:
        type: "integer"
        format: "int32"
        example: 48652
      quoteStatus:
        type: "string"
        example: "Processed"
      quoteApprovedDate:
        type: "string"
        format: "int32"
        example: "12/11/2018 00:12:45"
      quoteExpiryDate:
        type: "string"
        format: "int32"
        example: "12/11/2018 00:12:45"
      custUniqueId:
        type: "string"
        example: "K284818710P"
      vehicleInfo:
        $ref: "#/definitions/BasicVehicleDataDto"
      pricingDetails:
        $ref: "#/definitions/PricingDetailsDto"
      discountDetails:
        $ref: "#/definitions/DiscountDetailsDto"
      optionalEquipmentDto:
        $ref: "#/definitions/OptionalEquipmentDto"
      dealerFittedOptionsDto:
        $ref: "#/definitions/DealerFittedOptionsDto"
      plannedRetailDate:
        type: "string"
        format: "int32"
        example: "12/11/2018 00:12:45"
    description: "Dto object that returns the quote object, after creation"
    example:
      optionalEquipmentDto:
        optionsDetails:
          string1: "value1"
          string2: "value2"
      vehicleInfo:
        EngNo: 38746297
        VinNo: "W273647619E248762"
        VmsNo: 3456386
        VehicleModel: "A 180 d Automatic"
      stId: 48652
      quoteId: 1000801
      quoteStatus: "Processed"
      discountDetails:
        swtModelCode: "AB38472"
        discounts:
          fleetDiscount: "7236.00"
          custDiscount: "67.00"
        discountId: 1
      custId: 123
      plannedRetailDate: "12/11/2018 00:12:45"
      custUniqueId: "K284818710P"
      dealerFittedOptionsDto:
        optionsDetails:
          do1: "value1"
          do2: "value2"
      quoteApprovedDate: "12/11/2018 00:12:45"
      pricingDetails:
        TotalExtrasPriceExclVat: 34638
        Co2TaxExclVat: 34638
        BaseModelPriceExclVat: 34638
        vatCurr: "SGD"
        priceDate: "12/11/2018 00:12:45"
        Co2TaxInclVat: 34638
        vatRate: "1.23"
        TotalExtrasPriceInclVat: 34638
        BaseModelPriceInclVat: 34638
      quoteExpiryDate: "12/11/2018 00:12:45"
  OptionalEquipmentDto:
    type: "object"
    properties:
      optionsDetails:
        type: "array"
        example:
          string1: "value1"
          string2: "value2"
        items:
          $ref: "#/definitions/OptionalEquipmentDto_optionsDetails"
    description: "Dto object for holding optional equipment"
    example:
      optionsDetails:
        string1: "value1"
        string2: "value2"
  DealerFittedOptionsDto:
    type: "object"
    properties:
      optionsDetails:
        type: "array"
        example:
          do1: "value1"
          do2: "value2"
        items:
          $ref: "#/definitions/OptionalEquipmentDto_optionsDetails"
    description: "Dto object for holding dealer fitted options"
    example:
      optionsDetails:
        do1: "value1"
        do2: "value2"
  DiscountDetailsDto:
    type: "object"
    properties:
      discountId:
        type: "integer"
        example: 1
      swtModelCode:
        type: "string"
        example: "AB38472"
      discounts:
        type: "array"
        example:
          fleetDiscount: "7236.00"
          custDiscount: "67.00"
        items:
          $ref: "#/definitions/DiscountDetailsDto_discounts"
    description: "Dto object for holding discount details of a vehicle"
    example:
      swtModelCode: "AB38472"
      discounts:
        fleetDiscount: "7236.00"
        custDiscount: "67.00"
      discountId: 1
  PricingDetailsDto:
    type: "object"
    properties:
      BaseModelPriceInclVat:
        type: "integer"
        format: "double"
        example: 34638
      BaseModelPriceExclVat:
        type: "integer"
        format: "double"
        example: 34638
      TotalExtrasPriceInclVat:
        type: "integer"
        format: "double"
        example: 34638
      TotalExtrasPriceExclVat:
        type: "integer"
        format: "double"
        example: 34638
      Co2TaxInclVat:
        type: "integer"
        format: "double"
        example: 34638
      Co2TaxExclVat:
        type: "integer"
        format: "double"
        example: 34638
      vatRate:
        type: "integer"
        format: "double"
        example: "1.23"
      vatCurr:
        type: "string"
        example: "SGD"
      priceDate:
        type: "string"
        format: "int32"
        example: "12/11/2018 00:12:45"
    description: "Dto object that holds the Pricing related information"
    example:
      TotalExtrasPriceExclVat: 34638
      Co2TaxExclVat: 34638
      BaseModelPriceExclVat: 34638
      vatCurr: "SGD"
      priceDate: "12/11/2018 00:12:45"
      Co2TaxInclVat: 34638
      vatRate: "1.23"
      TotalExtrasPriceInclVat: 34638
      BaseModelPriceInclVat: 34638
  FleetDetailsDto:
    type: "object"
    required:
    - "fleetChannelId"
    - "fleetVolume"
    properties:
      fleetChannelId:
        type: "integer"
        format: "int32"
        example: 1
      fleetVolume:
        type: "integer"
        format: "int32"
        example: 2
    description: "Dto object for holding the fleet details"
    example:
      fleetVolume: 2
      fleetChannelId: 1
  FinProdDetailsDto:
    type: "object"
    required:
    - "monthlyPayment"
    - "productId"
    - "productTerm"
    properties:
      productId:
        type: "integer"
        format: "int32"
        example: 3454
      productTerm:
        type: "integer"
        format: "int32"
        example: 12
      monthlyPayment:
        type: "integer"
        format: "float"
        example: 1000
    description: "Dto object for holding the financial product related information"
    example:
      productId: 3454
      monthlyPayment: 1000
      productTerm: 12
  STS.SalesTransaction:
    type: "object"
    required:
    - "CreatedDate"
    - "CustId"
    - "ModifiedDate"
    - "StId"
    - "StsCurrentStage"
    - "StsCurrentStatus"
    properties:
      StId:
        type: "integer"
        format: "int32"
        example: 1
      QuoteId:
        type: "string"
        example: "7017480851"
      CustId:
        type: "integer"
        format: "int32"
        example: 123
      CreatedDate:
        type: "string"
        format: "int32"
        example: "12/11/2018 00:12:45"
      ModifiedDate:
        type: "string"
        format: "int32"
        example: "13/11/2018 00:12:45"
      StsCurrentStage:
        type: "integer"
        format: "int32"
        example: 1
      StsCurrentStatus:
        type: "integer"
        format: "int32"
        example: 1
    description: "Underlying DB Object for Sales Txns"
  STS.SalesTransactionStage:
    type: "object"
    required:
    - "StsStage"
    - "StsStageDesc"
    properties:
      StsStage:
        type: "integer"
        format: "int32"
        example: 1
      StsStageDesc:
        type: "string"
        example: "Sales Query"
    description: "Underlying DB object that stores the stages of a sales transaction"
  STS.SalesTransactionStatus:
    type: "object"
    required:
    - "StsStatus"
    - "StsStatusDesc"
    properties:
      StsStatus:
        type: "integer"
        format: "int32"
        example: 1
      StsStatusDesc:
        type: "string"
        example: "Sales Transaction Created"
    description: "Underlying DB object that stores the statuses of a sales transaction"
  OptionalEquipmentDto_optionsDetails:
    properties:
      optionType:
        type: "string"
      optionDesc:
        type: "string"
  DiscountDetailsDto_discounts:
    properties:
      discountType:
        type: "string"
      discountValue:
        type: "number"
        format: "double"
